function Register-WayforgeCI {
    <#
    .SYNOPSIS
        Writes a CI workflow that runs the gate engine at merge time.

    .DESCRIPTION
        Generates a CI workflow (GitHub Actions) that runs
        `Invoke-WayforgeGate -Stage ci` on pull requests. This is the
        fail-closed floor: because it runs server-side as a required check, no
        client flag (`--no-verify`, `--dangerously-bypass-*`) can route around
        it. It runs the same engine as the local git hooks, so what blocks a
        commit also blocks a merge.

        Enabling it as a *required* check still needs branch protection, which is
        a repository setting this function does not change.

    .PARAMETER ProjectPath
        A path inside the target repository. Defaults to the current directory.

    .PARAMETER Provider
        The CI provider to target. Currently 'github' (GitHub Actions).

    .EXAMPLE
        Register-WayforgeCI

        Writes .github/workflows/wayforge-gate.yml so the same gates run as a
        pull-request check. Make it a required check via branch protection.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType('PSWayforge.CIRegistration')]
    param(
        [string] $ProjectPath = (Get-Location).Path,

        [ValidateSet('github')]
        [string] $Provider = 'github'
    )

    $root = Resolve-WayforgeGitRoot -Path $ProjectPath

    switch ($Provider) {
        'github' {
            $workflowDir = Join-Path $root '.github/workflows'
            if (-not (Test-Path $workflowDir)) { New-Item -ItemType Directory -Path $workflowDir -Force | Out-Null }
            $path = Join-Path $workflowDir 'wayforge-gate.yml'

            $content = @'
# Generated by PSWayforge (Register-WayforgeCI).
# Runs the same gate engine as the local git hooks: what blocks a commit blocks
# a merge. This is the fail-closed floor - make it a required status check via
# branch protection so no client-side flag can bypass it.
#
# Requires the PSWayforge module to be installable on the runner. If PSWayforge
# is not published to the PowerShell Gallery, replace the install step with your
# vendoring approach (e.g. clone the module and Import-Module by path).
name: wayforge-gate

on:
  pull_request:

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # full history so origin/<base>...HEAD resolves

      - name: Install dependencies
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSWayforge, powershell-yaml -Force -Scope CurrentUser
          # Install any external tools your `run:` gates need here (gitleaks, semgrep, ...).

      - name: Run Wayforge gate
        shell: pwsh
        env:
          WAYFORGE_BASE_REF: origin/${{ github.event.pull_request.base.ref }}
        run: |
          Import-Module PSWayforge
          $report = Invoke-WayforgeGate -Stage ci -AsHook ci
          exit $report.ExitCode
'@
            $content = ($content -replace "`r`n", "`n")

            if ($PSCmdlet.ShouldProcess($path, 'Write CI gate workflow')) {
                [System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
            }

            [PSCustomObject]@{
                PSTypeName = 'PSWayforge.CIRegistration'
                Provider   = 'github'
                File       = $path
            }
        }
    }
}
